const mongoose=require("mongoose");

const batchSchema=new mongoose.Schema({
    clientId:{
        type:String,
        requied:true
    },
    Pimage:{ 
        type:String,
        requied:true
    },
    QROnprod:{ 
        type:String,
        default:""
    },
    QRDetails:[
        {
            quantity:{
                type:Number,
            },
            createdAt:{
                type:Date,
            },
            generatedBy:{
                type:String
            }
        }
    ],
    trackingQrDetails:[
        {
            quantity:{
                type:Number,
            },
            createdAt:{
                type:Date,
            },
            generatedBy:{
                type:String
            }
        }
    ],
    prodName:{
        type:String,
        required:true
    },
    brand:{
        type:String,
        required:true
    },
    status:{
        type:String,
        default:"unblocked"
    },
    mrp:{
        type:Number,
        required:true
    },
    mfgDate:{
        type:Date,
        required:true
    },
    shelfLife:{
        type:Number,
        default:0
    },
    batchNo:{
        type:String,
        required:true
    },
    statusChangeDate:{
        type:Date,
        default:null
    },
    reasonStatusChange:{
        type:String,
        default:null
    },
    statusChangeBy:{
        type:String,
        default:null
    },
    warrantyApp:{
        type:Boolean,
        required:true
    },
    warrantyPeriod:{
        type:Number,
        default:0
    },
    expiryDate:{
        type:Date,
        default:null
    },
    serialNo:{
        type:String,
        default:null
    },
    cashBackApp:{
        type:Boolean, 
        required:true
    },
    cashBackPts:{
        type:Number,
        default:0
    },
    costStructure:{
        type:Object,
        required:true
    },
    dor:{
        type:String,
        required:true
    },
    tor:{
        type:String,
        required:true
    },
    type:{
        type:Number,
        required:true
    },
    // noOfAppends:{
    //     type:String,
    //     default:'0',
    //     required:true
    // },
    manuLicenseNo:{
        type:String,
        default:""
    },
    manuAdd:{
        type:String,
        default:""
    },
    addDetails:{
        type:String,
        default:""
    },
    extraImages:[
        {
            url:{
                type:String,
                default:""
            }
        }
    ]
},{timestamps:true});

module.exports=mongoose.model("Batch",batchSchema);